#!/bin/bash -e

REMOTE='https://mirrors.edge.kernel.org/linuxmint-packages/pool/upstream/c/chromium/'
RELEASES='focal/una jammy/victoria'
LINKS='jammy/kinetic jammy/lunar jammy/mantic'
EMAIL='phd@phd.re'

umask 022
