#!/bin/bash -e

REMOTE='https://mirrors.edge.kernel.org/linuxmint-packages/pool/upstream/c/chromium/'
REDIRECT='1'
RELEASES='focal/una jammy/virginia noble/zara'
LINKS='jammy/kinetic jammy/lunar jammy/mantic noble/oracular noble/plucky'
EMAIL='phd@phd.re'

umask 022
